version: '3.8'

services:
  # Base image build
  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    image: rag-ingest-base:latest

  # Main workflow worker
  workflow:
    build:
      context: .
      dockerfile: docker/workflow.Dockerfile
    depends_on:
      - base
    env_file: .env
    volumes:
      - ./assets:/app/assets
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Thumbnail generation worker
  thumbnail:
    build:
      context: .
      dockerfile: docker/thumbnail.Dockerfile
    depends_on:
      - base
    env_file: .env
    volumes:
      - ./assets:/app/assets
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Page parsing worker
  parsing:
    build:
      context: .
      dockerfile: docker/parsing.Dockerfile
    depends_on:
      - base
    env_file: .env
    volumes:
      - ./assets:/app/assets
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Text chunking worker
  chunking:
    build:
      context: .
      dockerfile: docker/chunking.Dockerfile
    depends_on:
      - base
    env_file: .env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Embedding worker
  embedding:
    build:
      context: .
      dockerfile: docker/embedding.Dockerfile
    depends_on:
      - base
    env_file: .env
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    depends_on:
      - temporal
      - vector_db

  temporal:
    build:
      context: .
      dockerfile: docker/Dockerfile.temporal
    depends_on:
      - vector_db

  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379" 